### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by HaoZeke** [dariober/sympy-books#1]
Hi @dariober! I was wondering about the licensing of these. In particular, I'm looking to expand the current [symengine](https://github.com/symengine) documentation and I think these examples would be great. I'm cc'ing some of the other developers in case they have comments as well. @certik @asmeurer.

**Comment by dariober** [comment]
Hi- thanks for your interes! I add a license, MIT, so you can use the repository as you wish. But really, this is mostly unsorted code for me to learn stuff and play around - be quite careful in using it!

**Comment by HaoZeke** [comment]
Thanks a ton, I'll be careful ^_^
